### ISSUE TITLE
Often crashing

### ISSUE THREAD

**Issue by hanson1024** [BlueChilli/flutter_uploader#26] opened 2019-10-22 13:03 UTC
self.runningTaskById[taskId] = UploadTask(taskId: taskId, status: .running, progress: Int(progress), tag: runningTask?.tag)

let runningTask = self.runningTaskById[taskId]

URLSessionDidSendBodyData: taskId: chillisource.flutter_uploader.upload.background.7, byteSent: 32768, totalBytesSent: 360448, totalBytesExpectedToSend: 1049738, progress:34.0

EXC_BAD_ACCESS(code=EXC_I386_GPFLT)

**Comment by onikiri2007** [comment] 2019-11-05 23:48
this should be fixed with 1.2.0

**Closed by onikiri2007** 2019-11-05 23:48 UTC

**Comment by ragnor-rs** [comment] 2019-12-02 11:37
Unfortunately, on Simulator, it is still quite easy to reproduce with 1.2.0

#0	0x00007fff50b9378b in objc_msgSend ()
#1	0x000000010eca2d13 in Dictionary._Variant.setValue(_:forKey:) ()
#2	0x000000010ee98f8d in specialized Dictionary.subscript.setter ()
#3	0x000000010ec72792 in Dictionary.subscript.setter ()
#4	0x000000010960cf39 in SwiftFlutterUploaderPlugin.urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:) at /Users/reist/Library/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_uploader-1.2.0/ios/Classes/SwiftFlutterUploaderPlugin.swift:617
#5	0x000000010960d315 in @objc SwiftFlutterUploaderPlugin.urlSession(_:task:didSendBodyData:totalBytesSent:totalBytesExpectedToSend:) ()
#6	0x00007fff22f2dd89 in ___lldb_unnamed_symbol8580$$CFNetwork ()
#7	0x00007fff25732d61 in __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ ()
#8	0x00007fff25732c59 in -[NSBlockOperation main] ()
#9	0x00007fff25735be6 in __NSOPERATION_IS_INVOKING_MAIN__ ()
#10	0x00007fff25731e59 in -[NSOperation start] ()
#11	0x00007fff25736540 in __NSOPERATIONQUEUE_IS_STARTING_AN_OPERATION__ ()
#12	0x00007fff2573604a in __NSOQSchedule_f ()
#13	0x000000010f6cd3c9 in _dispatch_block_async_invoke2 ()
#14	0x000000010f6bed48 in _dispatch_client_callout ()
#15	0x000000010f6c16ba in _dispatch_continuation_pop ()
#16	0x000000010f6c0ac5 in _dispatch_async_redirect_invoke ()
#17	0x000000010f6d028c in _dispatch_root_queue_drain ()
#18	0x000000010f6d0b96 in _dispatch_worker_thread2 ()
#19	0x00007fff51c016d5 in _pthread_wqthread ()
#20	0x00007fff51c0157b in start_wqthread ()
Enqueued from com.apple.NSURLSession-work (Thread 35) Queue : com.apple.NSURLSession-work (serial)
#0	0x000000010f6c2c5d in dispatch_async ()
#1	0x00007fff25730010 in __NSOQSchedule ()
#2	0x00007fff25733e6c in __addOperations ()
#3	0x00007fff22f2a706 in ___lldb_unnamed_symbol8413$$CFNetwork ()
#4	0x000000010f6bddd4 in _dispatch_call_block_and_release ()
#5	0x000000010f6bed48 in _dispatch_client_callout ()
#6	0x000000010f6c55ef in _dispatch_lane_serial_drain ()
#7	0x000000010f6c61b5 in _dispatch_lane_invoke ()
#8	0x000000010f6d1a4e in _dispatch_workloop_worker_thread ()
#9	0x00007fff51c0171b in _pthread_wqthread ()
#10	0x00007fff51c0157b in start_wqthread ()
Enqueued from com.apple.NSXPCConnection.m-user.com.apple.nsurlsessiond (Thread 7) Queue : com.apple.NSXPCConnection.m-user.com.apple.nsurlsessiond (serial)
#0	0x000000010f6c2c5d in dispatch_async ()
#1	0x00007fff22e3bdbb in ___lldb_unnamed_symbol3257$$CFNetwork ()
#2	0x00007fff23c561cc in __invoking___ ()
#3	0x00007fff23c532df in -[NSInvocation invoke] ()
#4	0x00007fff258d756c in __NSXPCCONNECTION_IS_CALLING_OUT_TO_EXPORTED_OBJECT__ ()
#5	0x00007fff258d6068 in -[NSXPCConnection _decodeAndInvokeMessageWithEvent:flags:] ()
#6	0x00007fff258d78b8 in message_handler ()
#7	0x00007fff51c3debc in _xpc_connection_call_event_handler ()
#8	0x00007fff51c3e246 in _xpc_connection_mach_event ()
#9	0x000000010f6bede8 in _dispatch_client_callout4 ()
#10	0x000000010f6d8736 in _dispatch_mach_msg_invoke ()
#11	0x000000010f6c540e in _dispatch_lane_serial_drain ()
#12	0x000000010f6d95f1 in _dispatch_mach_invoke ()
#13	0x000000010f6c540e in _dispatch_lane_serial_drain ()
#14	0x000000010f6c61b5 in _dispatch_lane_invoke ()
#15	0x000000010f6d1a4e in _dispatch_workloop_worker_thread ()
#16	0x00007fff51c0171b in _pthread_wqthread ()
#17	0x00007fff51c0157b in start_wqthread ()

**Comment by ened** [comment] 2019-12-02 11:39
@ragnor-rs please open a separate issue and also show the arguments passed to the Dart methods. This looks like an empty / null value in a parameters/headers dictionary and we probably just need to add some null-checks.

**Comment by ragnor-rs** [comment] 2019-12-02 11:56
@ened please see https://github.com/BlueChilli/flutter_uploader/issues/39
