### ISSUE TITLE
Wrong Accept header in Android 

### ISSUE THREAD

**Issue by levichevdmitry** [BlueChilli/flutter_uploader#85] opened 2020-08-26 17:19 UTC
On android platform incorrect Accept headers:
Now - application/json **;** charset=utf-8
Must be - application/json **,** charset=utf-8
See: https://github.com/BlueChilli/flutter_uploader/blob/dbdc47d33905cc05ae939ab2d5bec2e678923703/android/src/main/java/com/bluechilli/flutteruploader/UploadWorker.java#L217
Because- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept
It was broken work in restify server on Node.JS

**Comment by ened** [comment] 2020-09-03 15:02
@levichevdmitry thx & the issue is resolved in #86 , please give it a try

**Closed** 2020-09-10 08:58 UTC
Labels: android, bug
