### ISSUE TITLE
New Background modes

### ISSUE THREAD

**Issue by clementjouannet** [BlueChilli/flutter_uploader#44] opened 2020-01-22 14:33 UTC
Since Xcode 11, a new mode appeared in the "Background Modes" section of the iOS project.

![Capture d’écran 2020-01-22 à 15 31 29](https://user-images.githubusercontent.com/11754420/72902804-658fce00-3d2c-11ea-82e4-2fb1d3c8a918.png)

The "Background processing" needs to be enable, otherwise the app crash.

**Comment by ragnor-rs** [comment] 2020-02-10 09:04
@clementjouannet would you please provide a related stack trace?

**Comment by clementjouannet** [comment] 2020-02-13 13:16
@ragnor-rs After further tests, i realized that the problem wasn't from the "Background processing" not enable. I was launching too many tasks at the same time, and the crash was coming from this. By enabling only one task running at the same time, the app doesn't crash anymore

**Comment by ened** [comment] 2020-07-16 08:23
Seems like this issue is a duplicate of #57

**Closed by ened** 2020-07-16 08:23 UTC
